### ISSUE TITLE
Bug: Support m1 architecture

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/asdf-aws-vault#3]
@kadikraman 's mac is trying to download `https://github.com/99designs/aws-vault/releases/download/v6.3.1/aws-vault-linux-aarch64` on a new M1 mac when it should be aiming for `https://github.com/99designs/aws-vault/releases/download/v6.3.1/aws-vault-darwin-arm64.dmg`

M1 env var values on machine natively.

platform="darwin"
arch="arm64"

I am suspecting that the download is via Docker :)

**Comment by tptee** [comment]
Fixed in v1.0.1! Thanks @kadikraman for testing!!
